### ISSUE TITLE
Script tag should come last in the body tag

### ISSUE THREAD

**Issue by inezabonte** [marisabrantley/constructive-and-co#1]
https://github.com/marisabrantley/constructive-and-co/blob/f373d46ad0c59416b5a026fe7fc624958856c653/index.html#L8-L10

**Comment by inezabonte** [comment]
I know your goal was to put the greeting in the middle.
Maybe for that you can do this;

In your HTML insert a h3 tag where you had previously placed the script tag
and give it a default text like `Welcome` in case JS fails to load. and also give it an id.

```html
<body>
    <h1>Constructive &amp; Co.</h1> 
    <h3 id="greeting">Welcome!</h3>
    <p>For all orders and inquires please call <em>555-3344.</em></p> 
    <script src="js/add-content.js"></script> 
 </body>
```

Then in your javascript use the `getElementById` function to retrieve 
the element that has the corresponding id (in this case the id is "greeting").
After that you can add your if statements to give the appropriate greeting

```js
const greeting = document.getElementById("greeting")

const today = new Date();  // Create a new date object
const hourNow = today.getHours();  // Find the current hour

if (hourNow > 18) {
    greeting.textContent = 'Good evening!';
} else if (hourNow > 12) {
    greeting.textContent = 'Good afternoon!';
} else if (hourNow > 0) {
    greeting.textContent = 'Good morning!';
} else {
    greeting.textContent = 'Welcome!';
}

```

**Comment by marisabrantley** [comment]
Thanks for taking a look at this, Ineza! The exercise was from a book and I went with how they wrote it. I'm not sure why they went that route. :thinking: I'll be updating the code with your suggestions. 

Thank you also for offering the suggestions via a GitHub issue. This is a first for me! Thanks for the learning experience. :thumbsup:

**Comment by inezabonte** [comment]
You're welcome Marisa. Glad to be of assistance 🙂
